### ISSUE TITLE
No module named 'vgg16module'

### ISSUE THREAD

**Issue by Lupins** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#1]
This error comes up on line 13 when running temporalneturfd.py, with python3.

I tryed using the vgg16module.py from project deeplearning-activity-recognition, the problem jumped to: No module named 'imagenet_utils'.

Keras 2.1.2 is installed. weights.h5, flow_mean.mat, labels_urfd.h5 and labels_urfd.h5 are also included in the folder.

**Comment by AdrianNunez** [comment]
Hi @Lupins 

I have just added the vgg16module.py to the repository. Sorry for the inconvenient. It should not give you the error you mention now.

**Comment by Lupins** [comment]
Solved, thank you.
