### ISSUE TITLE
FDD Dataset Missing Labels

### ISSUE THREAD

**Issue by vietdzung** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#10]
Hi Adrian, thank you for putting your code on GitHub, it has been really useful for me as I work on my own project. I want to ask about where you get the labels for the FDD dataset. Specifically, for Lecture_room and Office 1 & 2, I couldn't find the labels in the original dataset on this website: [http://le2i.cnrs.fr/Fall-detection-Dataset](http://le2i.cnrs.fr/Fall-detection-Dataset). Did you manually label the videos in those folders yourself, or did you get it from somewhere else, perhaps the author of the dataset? Thank you very much in advance!

**Comment by AdrianNunez** [comment]
Hello,

I couldn't find them either, so I did a cross-validation training and evaluation with the rest of the dataset.

I must say I am currently working on some fixes and improvements with the code and the data, which are shown in the github repository updates. I may need a day or two to submit everything about the FDD dataset, in case you want to use it. The URFD dataset is already updated.

**Comment by vietdzung** [comment]
I see, thanks for quick response!

**Comment by Andrea-Apicella** [comment]
Hi, the FDD dataset seems unaviable on the website http://le2i.cnrs.fr/Fall-detection-Dataset
Do you know how I could download it?

Thank you!

**Comment by CrazyTanoli** [comment]
> Hi, the FDD dataset seems unaviable on the website http://le2i.cnrs.fr/Fall-detection-Dataset
> Do you know how I could download it?
> 
> Thank you!

Hi, i am facing same problem did you find any solution or any other dataset

**Comment by Andrea-Apicella** [comment]
Hi, I didn't find a solution to obtain FDD dataset. I used Multicam ( http://www.iro.umontreal.ca/~labimage/Dataset/ <http://www.iro.umontreal.ca/~labimage/Dataset/> ) and URFD (http://fenix.univ.rzeszow.pl/~mkepski/ds/uf.html <http://fenix.univ.rzeszow.pl/~mkepski/ds/uf.html>) instead.

I hope this can help you!

> Il giorno 23 mag 2020, alle ore 08:15, CrazyTanoli <notifications@github.com> ha scritto:
> 
> —
