### ISSUE TITLE
How to test on a new set of optical flow image

### ISSUE THREAD

**Issue by YunboLyu** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#11]
Hi! I'm testing this excellent project on my server, my question may be silly as I am just begin to learn about computer vision hahaha.  I have already re-trained this model, and I noticed there is a function called 'test_video' in temporalneturfd.py. Is it used to test on a new video? If so, what should I do with the two returned variables called 'predictions' & 'truth' to know whether there is a fall action? Thank you very much.

**Comment by AdrianNunez** [comment]
Hi,

The function to test the network for a video is still not tested, so I cannot guarantee that it works. Anyway, given the two arrays, predictions and truth (which are just individual predictions within the video), many strategies could be applied to give a single output/prediction for the whole video, such as averaging results (this could be applied if the video has only one label).

**Comment by YunboLyu** [comment]
Thanks Adrian. So I will try to write one myself, haha.
