### ISSUE TITLE
This line

### ISSUE THREAD

**Issue by gpspelle** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#12]
https://github.com/AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow/blob/e88731459d7f8c40f9c087f35a388407ee8670fc/temporalneturfd.py#L398

This line and its relation with zeros_full, train_index_falls and the ellipsis slicing operator totally deserve a comment before applying it. 

Also, lines 368, 369, 373 and 376 are useless right?

**Comment by AdrianNunez** [comment]
Hi,

> This line and its relation with zeros_full, train_index_falls and the ellipsis slicing operator totally deserve a comment before applying it.

I will try to improve the comments.

> Also, lines 368, 369, 373 and 376 are useless right?

Lines 368 and 369 (sort operation) were required, otherwise an error was thrown. I will mark 373 and 376 to be removed in the next update. Thank you for pointing that out.

**Comment by gpspelle** [comment]
But aren't they already sorted before you call a sort? Because np.where vanishes the input array from left to right and already give indexes in increasing order?
