### ISSUE TITLE
Test Fall detection on a new video

### ISSUE THREAD

**Issue by simoooB** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#14]
Hello,

First, thanks for sharing this work.
My question is about how can i apply your algorithm to a new video? how should i do?
(I tried to do that by passing frames to the model but didnt work)

Thanks a lot

**Comment by AdrianNunez** [comment]
Hello,

You need to compute the optical flow stacks from your video (you can see it [here](https://github.com/AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow/blob/master/temporalneturfd.py#L182) in the code), then pass each of them to the classifier and, finally, decide what to do with each of the predictions to obtain a global prediction for the video. For example, you could average the softmax activations of each of the stacks (an average per class) and get the highest score one as the predicted class of the video.
