### ISSUE TITLE
Not Able To Follow The Codes

### ISSUE THREAD

**Issue by sumeetssingh** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#2]
Hello,
I read paper and found quite interesting. I want to replicate it for my own dataset. The codes listed here are very difficult to understand. Could you please include a read me file. Where are the weights obtained after training the network with action recognition datasets. Please help me out.

**Comment by AdrianNunez** [comment]
Hi,

thanks for the interest in the paper and the code. I will be including comments in the code and adding a README file with all the necessary steps to follow in the next days.

Regards.

**Comment by sumeetssingh** [comment]
Hello,
Thanks a lot for updating comments. Now its very clear.However, it will be very much helpful if you could also add the script for testing the code using a single video for actual testing. I mean the inference part using any unseen video of fall/no fall. Moreover, I found the URFD dataset contains image sequences not actual videos, but the optical flow scripts which you have mentioned in the paper, accepts videos for generating OF images and the RGB images. Could you please explain a bit how to pass images sequences to the optical flow generator script. 

Thanking You

**Comment by AdrianNunez** [comment]
Hi,

I will add a function to do inference over just one video (still, it will require optical flow images already processed). And regarding the problem with the URFD dataset, I will upload the modified script I used for processing image sequences instead of videos.

Thanks for the feedback!

**Comment by sumeetssingh** [comment]
Okay. Thank You Adrian.

**Comment by AdrianNunez** [comment]
Hi,

Sorry for the delay, I have forked and modified the original repository of the tool to create optical flow images so that it now allows to create them with a sequence of images. Here you have the link to the new repository: https://github.com/AdrianNunez/dense_flow. I have tested it with the URFD dataset without problems.

Regards.
