### ISSUE TITLE
Error running temporalneturfd.py

### ISSUE THREAD

**Issue by aviraljain99** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#20]
Hi,

I have tried running temporalneturfd.py to produce a trained model but I am getting the following error. I am not entirely sure how to go about fixing it. 

Any suggestions would be helpful. 

`Traceback (most recent call last):`
 ` File "temporalneturfd.py", line 602, in <module>`
   `    main()`
 ` File "temporalneturfd.py", line 422, in main`
`    train_indices_0, val_indices_0 = next(indices_0)`
 ` File "/opt/apps/anaconda3/envs/wmlce-v1.6.2-py3.7/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1323, in split`
    `for train, test in self._iter_indices(X, y, groups):`
 ` File "/opt/apps/anaconda3/envs/wmlce-v1.6.2-py3.7/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1624, in _iter_indices
    default_test_size=self._default_test_size)`
  `File "/opt/apps/anaconda3/envs/wmlce-v1.6.2-py3.7/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1734, in _validate_shuffle_split
    '(0, 1) range'.format(test_size, n_samples))`
`ValueError: test_size=50.0 should be either positive and smaller than the number of samples 480 or a float in the (0, 1) range`

Apologies for the bad formatting of the stack trace.

Thanks,

**Comment by AdrianNunez** [comment]
Hi,

I am not completely sure, but did you put test_size=50.0 somewhere? In the stratified shuffle split or cross validation, for example. It seems it was waiting an integer <480 or a float in range (0,1).

**Comment by aviraljain99** [comment]
@AdrianNunez 
Apologies for the late response but I managed to fix that error. On line 415 and 420, when passing `val_size/2` to the `test_size` parameter, `val_size/2` evaluates to 50.0 because it isn't using integer division. I fixed it by changing it to `val_size//2`.
