### ISSUE TITLE
Missing code lines in temporalnetmulticam.py

### ISSUE THREAD

**Issue by dararos** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#21]
First of all, I really appreciate your work on this. I think there's some missing part in your code in temporalnetmulticam file line #500 (approximately) where you are doing batch training.

**Comment by AdrianNunez** [comment]
Hi,

Thank for pointing this out! My computer must have messed something up and I accidentally pushed it. For the moment, copying that part from the other scripts should fix it.
