### ISSUE TITLE
test_video function

### ISSUE THREAD

**Issue by AnoshaRehan** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#22]
Hi!
I tried to run the test_video function:
saved_model = load_model("/home/VGG16/models/urfd_fold_5.h5")
    path = "/home/OF_NewData_1/Falls/fall_fall-01"
    pred, truth = test_video(saved_model, path, 1)
    print(pred)
But I keep on getting the error : ValueError: Error when checking : expected input to have 2 dimensions, but got array with shape (1, 20, 224, 224) 
at : prediction = feature_extractor.predict(np.expand_dims(flow[i, ...], 0))
I'm still very new to Neural Nets so I might be doing something wrong but I would really appreciate help on how to generate prediction using your code.
Thanks!

**Comment by AdrianNunez** [comment]
Hi,

This function is actually not tested, so I can't promise it will work, sorry for the inconvenience. Anyway, the error says that your feature extractor is expecting an input of 2 dimensions, which is quite strange, as it should be 4: (batch dimension, channels, height, width). How have you defined the model you are loading?

**Comment by AnoshaRehan** [comment]
Hello thank-you for the quick response...
I'm actually loading the last fold which was generated during training urfd_fold_5 as **saved_model = load_model("/home/VGG16/models/urfd_fold_5.h5")**
I would appreciate if you could guide me if I'm doing this incorrectly.
Also, is the sliding window necessary, can I simply generate a prediction on the set of optical flow frames of one video?

**Comment by AdrianNunez** [comment]
I'm lost with the error, to be honest. If I found it something I will post it here.

Regarding the sliding window, the strategy you use to decide the label of the video is customisable. That is, in my case I used a sliding window, but you could also sample N stacks from the video and decide the label by majority voting. In any case, you would need to modify the code for that.

**Comment by xiaoluobu** [comment]
Hi, AnoshaRehan

Have you solved your problem? I met the same problem.

**Comment by AnoshaRehan** [comment]
> Hi, AnoshaRehan
> 
> Have you solved your problem? I met the same problem.

Yes, I did. Basically I was the one making the mistake. So what I did was:
I added this line:
model.compile(optimizer=adam, loss='categorical_crossentropy',
                  metrics=['accuracy'])
    **print("Saving Feature Extraction Model ")
    model.save("./MyNewModel/FeatureExtractor")**
    do_training = True
    compute_metrics = True
    threshold = 0.5
    if do_training:
        h5features = h5py.File(features_file, 'r')
        h5labels = h5py.File(labels_file, 'r')
x--------------x
And then used the test_video function:
from keras.models import load_model, Model, Sequential
model = load_model("./MyNewModel/FeatureExtractor")
model2 = load_model("./MyNewModel/urfd_fold_5.h5")
video_path_fall = "./Videos/fall_fall-10"
preds_fall = test_video(model, video_path_fall)
model2 = load_model("./MyNewModel/urfd_fold_5.h5")
preds_fall= model2.predict(preds_fall)  // I removed the other argument for myself.
x--------------x
I hope this helps.

**Comment by xiaoluobu** [comment]
Hi Anosha,

It helps, thank you so much. 

I have another question:

I think the "fall_fall-*" is a training dataset. So we should find another untrained photo to test the model?

Best regards

**Comment by AnoshaRehan** [comment]
> Hi Anosha,
> 
> It helps, thank you so much.
> 
> I have another question:
> 
> I think the "fall_fall-*" is a training dataset. So we should find another untrained photo to test the model?
> 
> Best regards

Hi. I'm sorry I should have mentioned this before, I made my own video clips but named them with the same convention as the ones in the dataset. So yes, use your own or different videos than the ones from the dataset used for training.
I'm glad it helped you.
Best of luck!

**Comment by xiaoluobu** [comment]
Sounds great.
Thank you so much.

Best wishes




| |
luoxq0210
|
|
邮箱：luoxq0210@163.com
|

Signature is customized by Netease Mail Master

On 05/07/2020 12:17, Anosha Rehan wrote:

Hi Anosha,

It helps, thank you so much.

I have another question:

I think the "fall_fall-*" is a training dataset. So we should find another untrained photo to test the model?

Best regards

Hi. I'm sorry I should have mentioned this before, I made my own video clips but named them with the same convention as the ones in the dataset. So yes, use your own or different videos than the ones from the dataset used for training.
I'm glad it helped you.
Best of luck!

**Comment by AnoshaRehan** [comment]
> Sounds great. Thank you so much. Best wishes 

No problem.
I would appreciate if you are able to share any progress you make on this project if you don't mind.

**Comment by xiaoluobu** [comment]
Ok, We can communicate through email.




| |
luoxq0210
|
|
邮箱：luoxq0210@163.com
|

Signature is customized by Netease Mail Master

On 05/07/2020 14:58, Anosha Rehan wrote:

Sounds great. Thank you so much. Best wishes

No problem.
I would appreciate if you are able to share any progress you make on this project if you don't mind.

**Comment by xiaoluobu** [comment]
Hi, Anosha

How do you get the flow image?

**Comment by AnoshaRehan** [comment]
> Hi, Anosha
> 
> How do you get the flow image?

I used this code: https://github.com/AdrianNunez/dense_flow

**Comment by xiaoluobu** [comment]
Thank you. What's your version of opencv?

**Comment by AnoshaRehan** [comment]
> Thank you. What's your version of opencv?

3.4

**Comment by xiaoluobu** [comment]
Hi, Anosha

Five fold files are generated, why do you load the "urfd_fold_5.h5"? 

**model2 = load_model("./MyNewModel/urfd_fold_5.h5")**

I'm sorry I don't understand it. 

Best regards

**Comment by AnoshaRehan** [comment]
> Hi, Anosha
> 
> Five fold files are generated, why do you load the "urfd_fold_5.h5"?
> 
> **model2 = load_model("./MyNewModel/urfd_fold_5.h5")**
> 
> I'm sorry I don't understand it.
> 
> Best regards

I'm using the last fold model to make a classification which is the end goal of this project. I think the fifth fold has the best results.
I hope this helps in your understanding.
