### ISSUE TITLE
Transfer learning for slip detection

### ISSUE THREAD

**Issue by Kentwhf** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#23]
Hi Adrain,

I have properly reproduced your thesis experiment and would like to try my own dataset. I am wondering if a data set of slips can be possibly used to train for a slip detection system?

Usually, slips are harder to notice and the start point of slips is ambiguous.

**Comment by Kentwhf** [comment]
If it is possible, should I start over the training process with the vgg16 model mentioned in your README file? 

I also read some previous Issues on this project. Is the function "test_video" you design for inference on other videos but not yet completed? What about the 5-fold cross-validation? https://github.com/AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow/issues/2

**Comment by AdrianNunez** [comment]
Hi,

If the slip classification is also a binary classification problem and you have annotated data, you can. You would need optical flow images to use the system as it is, because the pre-training itself is done with these type of images. 

The 'test_video' function is not tested, I cannot assure it works properly. It is not part of the content of the paper, so I do not know if I will be able to work on it.

I don't get what you want to ask about the 5-fold CV, could you reformulate the question?

**Comment by Kentwhf** [comment]
Hi Adrain, 

Thanks for the advice. I think I confused myself with the concepts of training, test, evaluation sets.

I assume optical flow images are the only required output. I am now looking into a tool for generating optical flow pictures from videos. I have tried dense-flow as you suggested previously, but realized it only support Linux. Do you have any other recommendations for Windows10?

**Comment by dararos** [comment]
I also have the same issue running the dense-flow on my windows10 as well. Much appreciate it if you could point out where to get source code to generate optical flow images on Window.

**Comment by AdrianNunez** [comment]
Hi,

Sorry, I have no idea about those tools in Windows. I hope you find something useful.

**Comment by Kentwhf** [comment]
> I also have the same issue running the dense-flow on my windows10 as well. Much appreciate it if you could point out where to get source code to generate optical flow images on Window.

Hi,

I ended up writing my code to generate optical pictures by open-cv, as my raw data is a bunch of videos. I followed their [tutorial](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_video/py_lucas_kanade/py_lucas_kanade.html).

I believe you can find some other tools if you use RGB images as input.
