### ISSUE TITLE
bug in xxxxmulticam.py

### ISSUE THREAD

**Issue by dararos** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#26]
Hi Adrian,

After trying to fix a few bugs in the code file, I came to anther error after running.

"Too many arguments for format string" line #241 and #242
<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/45746765/73363326-87caa400-4276-11ea-96dc-66a68f0fba55.PNG">

I wasn't sure how you structure your dataset folder for Multicamera. I was wondering if you could upload parts of the dataset for the part of the experiment since the whole dataset would be huge.

best regards,

**Comment by AdrianNunez** [comment]
Hi,

Sorry for that, I still haven't fixed that script. In that case, I assume the ".format(nb_camera)" should be deleted (in the following print too), as the camera name is included in the variable "camera".

I need to work on Multicam, I hope I can update it soon. Sorry for the inconvenience.
