### ISSUE TITLE
something worng with temporalnetmulticam.py

### ISSUE THREAD

**Issue by Pandapan-Buaa** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#27]
in the file "temporalnetmulticam.py",the place of "classifier.fit" is wrong(which cause a syntax error）

**Comment by 1009303269** [comment]
the error occurs at line 34 by the way

**Comment by dararos** [comment]
line 34-38 should be placed at line# 502

**Comment by 1009303269** [comment]
Hi Adrain,
I‘ve read through the paper and finished the training of fdd/urfd dataset, and want to reproduce the experiment in section 4.6.
Could you please provide the "fall_experiments.json" file?(and may be other necessary files in temporalnetgeneral.py)
Thanks.

**Comment by AdrianNunez** [comment]
I have updated the code and that file should not be necessary anymore, sorry for the inconvenience.
