### ISSUE TITLE
Analysis of False Alarms and Missed Detection

### ISSUE THREAD

**Issue by Kentwhf** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#29]
Hi Andrian,

How did you analyze false alarms and missed detection as in 4.3.1 in your paper? 

I read through the scripts, but they don't seem to include such a part. Given the results in 4.3.1, I assume there is a way you can trace back the errors to their original video clips? 

I am not quite sure how to achieve that. Much appreciated if you could give me some enlightenment

**Comment by AdrianNunez** [comment]
Hi,

Sorry, I don't recall it, but i may have done it manually. In fact, to give those specific details I can't think of another way apart from looking each stack manually.
