### ISSUE TITLE
global name 'feature_extractor' is not defined

### ISSUE THREAD

**Issue by xiaoluobu** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#34]
Hi, 

I tried to use the function 'test_video', but it seems that no definition of input 'feature_extractor'.

Is it a function 'feature_extractor.py' or something else? Where can I get the input variable?

Thank you.

**Comment by AdrianNunez** [comment]
Hi,

Sorry but I haven't tested that function, it is not part of the paper. The 'feature_extractor' variable should be a CNN that takes as input optical flow stacks and outputs feature vectors.
