### ISSUE TITLE
real-time applications

### ISSUE THREAD

**Issue by xwr96** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#36]
HI！I want to ask this code can use in real-time applications or not? for example, I want to monitoring of the actions of the elderly immediately，can it work?

**Comment by AdrianNunez** [comment]
Hi,

You would need to adapt the code. In fact, you may require to generate optical flow images on-the-fly. There are neural networks that can estimate flow given two images that may work well for that.
