### ISSUE TITLE
test a video

### ISSUE THREAD

**Issue by mstc-xqp** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#39]
hello  how can i test  a depth image video?

**Comment by AdrianNunez** [comment]
Hi,

This network is not prepared for depth images, you would need to change the code.

**Comment by mstc-xqp** [comment]
> Hi,
> 
> This network is not prepared for depth images, you would need to change the code.

![image](https://user-images.githubusercontent.com/19384581/102964968-cff65300-4527-11eb-9b5c-c98fde1adc29.png)
how to use this?

**Comment by AdrianNunez** [comment]
That is an untested function, it is not used in the paper. I cannot guarantee that it works as it is supposed to. You need to input a feature extractor (CNN, for instance), a path to a folder with images of a video (from a fall or another event) and the ground truth label for the event.
