### ISSUE TITLE
Size of the Optical Flow Images

### ISSUE THREAD

**Issue by sumeetssingh** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#4]
Could you please specify the size of the computed optical flow images. If I am not wrong, it should be of 224 X 224 size. My optical flow image id of size 640 X 480. Do I need to resize it. Please help me in this.

Thank You

**Comment by AdrianNunez** [comment]
Hi,

I am very sorry for the delayed answer. I computed the optical flow images using images of size 224x224, you must resize them first.

Regards,
Adrián.
