### ISSUE TITLE
Original DataSet

### ISSUE THREAD

**Issue by Christopheraburns** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#6]
Adrian,  thanks for sharing this excellent work.  I have a need to train on my own dataset but I wont be in possession of that dataset for some time and I want to better understand your methodology.  I see that you had some storage limitations.  If I open an S3 bucket for you could you transfer the original dataset you used for training?  If not, could you link me to a good dataset I could use to train on?

**Comment by AdrianNunez** [comment]
Hi,

I am extremely sorry for my late response. [Here](https://drive.google.com/file/d/1TMnAe_lKPT3fm69noBGPEimX0iP2R56l/view?usp=sharing) you can download the URFD dataset. I hope you find it useful for testing the code.

**Comment by AlexyCarlier** [comment]
Hi Adrian,

I have a problem with the URFD dataset. Almost all of the folders in the No_Fall folder are empty, Could you re-upload the dataset with all the optical flows ?

Thanks you

Alexy
