### ISSUE TITLE
"vgg_16_weights" cannot download

### ISSUE THREAD

**Issue by urgonguyen** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#64]
Hi, Could you share the new link to download "vgg_16_weights" file? The old link cannot open!
Thank you!

**Comment by satyasaigudla** [comment]
vgg 16 weighted file is not working,Can you please share new  link or upload new weight file.

**Comment by AdrianNunez** [comment]
Links updated.

**Comment by urgonguyen** [comment]
Thank you!

**Comment by cxf2000** [comment]
> Thank you!

hi! I wonder if you have the vgg 16 weights, could you share with me? Thank you very much!

**Comment by cxf2000** [comment]
> vgg 16 weighted file is not working,Can you please share new link or upload new weight file.

hi! I wonder if you have the vgg 16 weights, could you share with me? Thank you very much!
