### ISSUE TITLE
Detect fall from Live Camera feed

### ISSUE THREAD

**Issue by ashokbugude** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#7]
Can I please know if it is possible to capture frames from Live camera and detect Fall from each frame or considering a set of consecutive frames.

**Comment by AdrianNunez** [comment]
Hi,

This method requires at least 10 frames as input and it is not suited for real-time applications due to the computational burden of the optical flow computation.

**Comment by ashokbugude** [comment]
Hi,

Thanks for your input.
Can I know if you are aware of any fall detection which does not involve much computational time (may be non neural network )

**Comment by AdrianNunez** [comment]
There are a lot of solutions using hand-crafted features or neural networks that work with raw images (with RNNs to model the time). You can check the [related works section](https://www.hindawi.com/journals/wcmc/2017/9474806/) in the paper for some examples. There are also various surveys on the topic, try to find the specific keywords of interest quickly (such as real-time).

**Comment by ashokbugude** [comment]
Thanks
