### ISSUE TITLE
Train the model on Multi-class problem ??  

### ISSUE THREAD

**Issue by scstu** [AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow#8]
I'd like to apply this architecture to solve a multi-class problem, instead of a binary classification of fall or no-fall sequence to many classes, like moving or doing some actions?

**Comment by AdrianNunez** [comment]
Hi,

Provide a description of what you want to do, please.

**Comment by scstu** [comment]
I just added the description   @AdrianNunez

**Comment by AdrianNunez** [comment]
Concerning the network you need to change the output operation and the number of units in the last layer of the classifier. I.e., from 1 unit and sigmoid operation to N units (N=number of actions) and softmax operation (to handle N possible outputs). 

In the data you need to change all the labels from the 0/1 to a one-hot encoding (sparse vectors that, for the class i, contain a 1 in the ith position and the rest are 0s). Also, balancing the dataset (if you want to do so) is different: with multiple classes you can limit the number of samples per class to the minimum, the average, the median... 

I believe these should be all the necessary changes. However, if you want to change the actual purpose of the code it may be better to start with a fresh project from scratch.
